<?php

/**
 * @file
 * Contains aspace_findingaid.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * Provides help text for ArchivesSpace Finding Aid migration module
 */
function aspace_findingaid_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.aspace_findingaid':
      return t('Provide ArchivesSpace Finding Aid migration to Drupal') ;
  }
}
