aspace_findingaid.settings:
  type: config_object
  label: 'ArchivesSpace Finding Aid Migration settings'
  mapping:
    archivesspace_base_uri:
      type: string
      label: 'ArchivesSpace API Endpoint'
      constraints:
        NotBlank:
          message: "Please set ArchivesSpace API uri."
    archivesspace_username:
      type: string
      label: 'ArchivesSpace API Username'
    archivesspace_password:
      type: string
      label: 'ArchivesSpace API Password'
