custom_findingaid_importer.settings:
  type: config_object
  label: 'Custom Finding Aid XSLT settings'
  mapping:
    xslt_aeon_files:
      type: sequence
      label: 'EAD XSLT files and descriptions'
      sequence:
        type: mapping
        label: 'configuration files pair'
        mapping:
          xslt_file:
            type: file
            label: 'Finding Aid XSLT'
          file_desc:
            type: string
            label: 'Fining Aid XSLT description'
            constraints:
              NotBlank:
                message: "Please set the Description for this finding aid XSLT"
    xslt_file_path:
      type: string
      label: 'EAD XSLT upload path'
